-- Crea la tabla
CREATE TABLE PYMES_ACTIVIDADES
   (	"ID" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ACTIVIDAD" VARCHAR2(20 BYTE), 
	"IDREQUERIMIENTO" VARCHAR2(20 BYTE), 
	"USUARIO" VARCHAR2(25 BYTE), 
	"ESTATUS_FOLIO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into PYMES_ACTIVIDADES
SET DEFINE OFF;

-- Crea la secuencia
CREATE SEQUENCE PYMES_ACTIVIDADES_SEQ1
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Modifica la secuencia
ALTER TABLE PYMES_ACTIVIDADES MODIFY ID NUMBER;

CREATE OR REPLACE EDITIONABLE TRIGGER PYMES_ACTIVIDADES_TRG
BEFORE INSERT ON PYMES_ACTIVIDADES 
FOR EACH ROW 
BEGIN
  IF INSERTING AND :NEW.ID IS NULL THEN
    SELECT PYMES_ACTIVIDADES_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
  END IF;
END;
/

-- Activa la secuencia
ALTER TRIGGER PYMES_ACTIVIDADES_TRG ENABLE;

-- Verifica que esxista
SELECT trigger_name, status
FROM user_triggers
WHERE trigger_name = 'PYMES_ACTIVIDADES_TRG';



